development:
  :host: localhost
  :user: mapper
  :pass: testing
  :vhost: /retcon
  :persistent: false
  :log_level: debug

production:
  :host: localhost
  :user: mapper
  :pass: testing
  :vhost: /retcon
  :persistent: true
  :log_level: info

test:
  :host: localhost
  :user: mapper
  :pass: testing
  :vhost: /retcon
  :persistent: false
  :log_level: debug

